# services:

#   app:
#     image: reservation-salles:latest
#     container_name: reservation-salles-app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - mysql
#     env_file:
#       - .env

#   mysql:
#     image: mysql:8.0
#     container_name: reservation-salles-mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: reservation_salles
#       MYSQL_USER: reservation_user
#       MYSQL_PASSWORD: reservation_password
#       MYSQL_ROOT_PASSWORD: root_password
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data: